stages:
  - ğŸ”— integration
  - ğŸ§ª test
  - ğŸ—ï¸ build
  - ğŸš€ deploy

.node_default:
  image: node:24-alpine
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - node_modules/

lint:
  stage: ğŸ§ª test
  extends: .node_default
  script:
    - npm ci
    - npm run lint

test:
  stage: ğŸ§ª test
  extends: .node_default
  script:
    - npm ci
    - npm run test:unit

integration_test:
  stage: ğŸ”— integration
  image: node:24-alpine
  services:
    - postgres:16-alpine
  variables:
    POSTGRES_DB: auth_test
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: $POSTGRES_DB
    DB_USERNAME: $POSTGRES_USER
    DB_PASSWORD: $POSTGRES_PASSWORD
    JWT_SECRET: test_jwt_secret_key_for_ci
    PEPPER: test_pepper_value_for_ci
    PORT: "3000"
  before_script:
    - npm ci
    - npx drizzle-kit push
  script:
    - npm run test:integration