stages:
  - ğŸ§ª test
  - ğŸ”— integration
  - ğŸ—ï¸ build
  - ğŸš€ deploy

.node_default:
  image: node:24-alpine
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - node_modules/

lint:
  stage: ğŸ§ª test
  extends: .node_default
  script:
    - npm ci
    - npm run lint

test:
  stage: ğŸ§ª test
  extends: .node_default
  script:
    - npm ci
    - npm run test:unit

integration_test:
  stage: ğŸ”— integration
  extends: .node_default
  script:
    - docker info