creation_rules:
  - path_regex: '.*secrets\.yaml$'
    # Encrypt only the Kubernetes Secret data fields, keep the structure readable
    encrypted_regex: '^(data|stringData)$'
    age:
      - age1a4v75pwnnanfr6rk3nvc4vpk7zy2tr4pt0qtfehssmw5f3ct899q593fad
