apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: auth
data:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: auth
data:
  # Database configuration
  DB_HOST: "{{ .Values.postgres.serviceName | quote }}.auth.svc.cluster.local"
  DB_PORT: {{ .Values.postgres.port | quote }}
  DB_NAME: {{ .Values.postgres.database | quote }}
  DB_USERNAME: {{ .Values.postgres.user | quote }}
  
  # Application configuration
  PORT: {{ .Values.auth.port | quote }}
  GRPC_PORT: {{ .Values.auth.grpcPort | quote }}
