apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2

  selector:
    matchLabels:
      app: {{ .Values.auth.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      serviceAccountName: {{ .Values.auth.serviceAccount.name }}
      containers:
       - name: {{ .Values.auth.name }}
         image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
         ports:
          - containerPort: {{ .Values.auth.port }}
            name: http
            protocol: TCP
         envFrom:
         - configMapRef:
             name: app-config
         - secretRef:
             name: secrets