apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.auth.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.auth.serviceAccount.roleArn }}
