apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.auth.serviceAccount.name }}
  namespace: auth
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.auth.serviceAccount.roleArn }}
