namespace: auth

certificateArn: "arn:aws:acm:eu-central-1:758280076486:certificate/946198a1-757c-4868-8e17-e2446087313f"

# App configuration
auth:
  name: auth-app
  port: 4000
  grpcPort: 50051
  image:
    repository: 758280076486.dkr.ecr.eu-central-1.amazonaws.com/focusboard/auth
    tag: latest
  replicas: 2
  serviceAccount:
    name: eks-service-account
    roleArn: "arn:aws:iam::758280076486:role/eks-auth-ecr-access-role"

  env:
    corsOrigin: "https://k8s-frontend-frontend-fe6f13f88d-1209588435.eu-central-1.elb.amazonaws.com,https://k8s-focus-focusing-a37b3eb8d5-1609498984.eu-central-1.elb.amazonaws.com"

# PostgreSQL configuration
postgres:
  serviceName: database
  port: 5432
  image:
    repository: postgres
    tag: "16-alpine"
  database: "auth"
  user: "test"